stages:
  download:
    wdir: ../../../
    cmd: pyrorisks download
    deps:
      - pyro_risks/pipeline/load.py
    outs:
      - .cache/data_registry/merged_era_viirs.csv
  train_xgboost:
    wdir: ../../../
    cmd: pyrorisks train --model XGBOOST --destination .cache/model_registry
    deps:
      - pyro_risks/pipeline/train.py
      - .cache/data_registry/merged_era_viirs.csv
    outs:
      - .cache/model_registry/XGBOOST.joblib
  train_rf:
    wdir: ../../../
    cmd: pyrorisks train --model RF --destination .cache/model_registry
    deps:
      - pyro_risks/pipeline/train.py
      - .cache/data_registry/merged_era_viirs.csv
    outs:
      - .cache/model_registry/RF.joblib
  evaluate:
    wdir: ../../../
    cmd: |
      pyrorisks evaluate --pipeline .cache/model_registry/RF.joblib --threshold .cache/model_registry/RF_threshold.json --prefix RF --destination .cache/metadata_registry 
      pyrorisks evaluate --pipeline .cache/model_registry/XGBOOST.joblib --threshold .cache/model_registry/XGBOOST_threshold.json --prefix XGBOOST --destination .cache/metadata_registry
    deps:
      - pyro_risks/pipeline/train.py
      - .cache/model_registry/XGBOOST.joblib
      - .cache/model_registry/RF.joblib
    metrics:
      - .cache/metadata_registry/XGBOOST_classification_report.json
      - .cache/metadata_registry/RF_classification_report.json
