name: builds

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build & run docker container
        env:
          CDS_UID: ${{ secrets.CDS_UID }}
          CDS_API_KEY: ${{ secrets.CDS_API_KEY }}
        run: PORT=8003 docker compose up -d --build
      - name: Ping containerized app
        run: sleep 5 && nc -vz localhost 8003
