name: push
on:
  push:
    branches: [ master ]

env:
  IMAGE_NAME: pyro-risks
  DOCKERHUB_USER: ${{ secrets.DOCKERHUB_LOGIN }}

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build docker
        run: docker compose build -t $DOCKERHUB_USER/$IMAGE_NAME:latest
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_LOGIN }}
          password: ${{ secrets.DOCKERHUB_PW }}
      - name: Push to hub
        run: docker push $DOCKERHUB_USER/$IMAGE_NAME:latest
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Push to container registry
        run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          docker tag $DOCKERHUB_USER/$IMAGE_NAME:latest $IMAGE_ID:latest
          docker push $IMAGE_ID:latest