name: Scheduled Scripts

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"

jobs:
  get-effis-fwi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Python Version
        uses: actions/setup-python@v4
        with:
          python-version: 3.10.5

      - uses: s-weigand/setup-conda@v1
        with:
          activate-conda: false
      - run: conda install conda-lock
      - run: conda-lock install -n pyro-risks pyrorisks.conda-lock.yml
      - run: conda activate pyro-risks

      - name: Install Poetry
        uses: snok/install-poetry@v1
        with:
          version: 1.8.1
          virtualenvs-create: false

      - name: Install dependencies
        run: poetry install

      - name: Get Today Effis Fwi
        run: poetry run python pyrorisks/platform_fwi/main.py
        env:
          AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          BUCKET_NAME: risk
          REGION_NAME: gra
          ENDPOINT_URL: https://s3.gra.io.cloud.ovh.net/

