name: web-server

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  docker-ready:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build & run docker
        env:
          CDS_UID: ${{ secrets.CDS_UID }}
          CDS_API_KEY: ${{ secrets.CDS_API_KEY }}
        run: PORT=8003 docker-compose up -d --build
      - name: Ping app inside the container
        run: sleep 5 && nc -vz localhost 8003
